### ISSUE TITLE
Error regarding MaAsLin2 log ratios

### ISSUE THREAD

**Issue by 411an13** [biocore/qadabra#58]
## Context
I tried running Qadabra on some prokaryotic species-level cluster (PSLC) counts data recently and ran into the error below. At first I thought it could have had something to do with the formatting of the index names in the .biom file I used as the table, but when I re-ran it I encountered the same error.

Specifically, there seems to be something awry when it comes to the calculation of log ratios for MaAsLin2. From what I could tell, there were 2 errors regarding the `log_ratio` function used to create `results/environment_comparisons/ml/maaslin2/log_ratios/log_ratios.pctile_15.tsv` and its pctile_20 counterpart (shown in the error message). The `log_ratios.pctile_20.tsv` file has 274 out of 687 total PSLCs in my original dataset/table, but the error message states that 137 are not in the columns (I'm not sure which columns it's referring to). I'm having trouble locating the `tmpflekjq_3.get_log_ratios.py` script mentioned in the error message so I figured I'd report this and ask to see if something like this has come up before.

## My questions
1. I pasted the header of the the `log_ratios.pctile_20.tsv` file at the bottom; are the values of the 3 rightmost columns supposed to be the same regardless of the feature_id? I don't know if that's causing the error but I figured I'd check.
2. How can I find the script that's mentioned in the error message so I can find out what the columns it's referring to are? When I `ls -a` the `.snakemake/scripts/` directory (looking for `tmpflekjq_3.get_log_ratios.py`) I don't see anything in it.
3. Have you encountered a similar issue?

Thank you and I'm happy to provide more info if needed.

## Code
Adding the dataset:
```
(qadabra_env) aphilliplt-osx:differential_abundance_analysis aphillip$ qadabra add-dataset \
> --workflow-dest my_qadabra \
> --table my_qadabra/data/slc_prok.biom \
> --metadata my_qadabra/data/environment_metadata.tsv \
> --name environment_comparisons\
> --factor-name group \
> --target-level sediment \
> --reference-level water \
> --verbose
```

Running the workflow:
```
(qadabra_env) aphilliplt-osx:differential_abundance_analysis aphillip$ cd my_qadabra/
(qadabra_env) aphilliplt-osx:my_qadabra aphillip$ snakemake --use-conda --cores 4
```

Portion of the error message:
```
Activating conda environment: .snakemake/conda/398bc325f983272b15d35276018e95bd_
Traceback (most recent call last):
  File "/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/scripts/tmpflekjq_3.get_log_ratios.py", line 41, in <module>
    lr_df = log_ratio(table, top_feats, bot_feats).reset_index()
...
File "/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['PSLC.198', 'PSLC.643', 'PSLC.340', 'PSLC.357', 'PSLC.32', 'PSLC.662',\n       'PSLC.38', 'PSLC.375', 'PSLC.389', 'PSLC.23',\n       ...\n       'PSLC.53', 'PSLC.668', 'PSLC.39', 'PSLC.40', 'PSLC.1', 'PSLC.270',\n       'PSLC.303', 'PSLC.291', 'PSLC.195', 'PSLC.683'],\n      dtype='object', length=137)] are in the [columns]"
[Fri Jan 12 17:30:38 2024]
Error in rule log_ratios:
    jobid: 143
    input: /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/data/slc_prok.biom, results/environment_comparisons/ml/maaslin2/pctile_feats/pctile_20.tsv
    output: results/environment_comparisons/ml/maaslin2/log_ratios/log_ratios.pctile_20.tsv
    log: log/environment_comparisons/log_ratios.maaslin2.pctile_20.log (check log file(s) for error details)
    conda-env: /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_

RuleException:
CalledProcessError in file /Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/site-packages/qadabra/workflow/rules/ml.smk, line 55:
Command 'source /Users/aphillip/anaconda3/bin/activate '/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_'; set -euo pipefail;  python /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/scripts/tmpflekjq_3.get_log_ratios.py' returned non-zero exit status 1.
  File "/Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/site-packages/qadabra/workflow/rules/ml.smk", line 55, in __rule_log_ratios
  File "/Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Traceback (most recent call last):
  File "/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/scripts/tmppagdql8a.get_log_ratios.py", line 41, in <module>
    lr_df = log_ratio(table, top_feats, bot_feats).reset_index()
...
File "/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['PSLC.198', 'PSLC.643', 'PSLC.340', 'PSLC.357', 'PSLC.32', 'PSLC.662',\n       'PSLC.38', 'PSLC.375', 'PSLC.389', 'PSLC.23',\n       ...\n       'PSLC.52', 'PSLC.665', 'PSLC.318', 'PSLC.685', 'PSLC.276', 'PSLC.349',\n       'PSLC.309', 'PSLC.632', 'PSLC.630', 'PSLC.359'],\n      dtype='object', length=103)] are in the [columns]"
[Fri Jan 12 17:30:39 2024]
Error in rule log_ratios:
    jobid: 122
    input: /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/data/slc_prok.biom, results/environment_comparisons/ml/maaslin2/pctile_feats/pctile_15.tsv
    output: results/environment_comparisons/ml/maaslin2/log_ratios/log_ratios.pctile_15.tsv
    log: log/environment_comparisons/log_ratios.maaslin2.pctile_15.log (check log file(s) for error details)
    conda-env: /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_

RuleException:
CalledProcessError in file /Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/site-packages/qadabra/workflow/rules/ml.smk, line 55:
Command 'source /Users/aphillip/anaconda3/bin/activate '/Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/conda/398bc325f983272b15d35276018e95bd_'; set -euo pipefail;  python /Users/aphillip/Library/CloudStorage/Desktop/Projects/counts_tables/differential_abundance_analysis/my_qadabra/.snakemake/scripts/tmppagdql8a.get_log_ratios.py' returned non-zero exit status 1.
  File "/Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/site-packages/qadabra/workflow/rules/ml.smk", line 55, in __rule_log_ratios
  File "/Users/aphillip/anaconda3/envs/qadabra_env/lib/python3.10/concurrent/futures/thread.py", line 58, in run
[Fri Jan 12 17:30:40 2024]
Finished job 92.
57 of 152 steps (38%) done
[Fri Jan 12 17:32:03 2024]
Finished job 9.
58 of 152 steps (38%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-01-12T171542.544654.snakemake.log
```

Header of the `log_ratios.pctile_20.tsv` file:
```
feature_id	location	pctile	num_feats
PSLC.198	numerator	20	137
PSLC.643	numerator	20	137
PSLC.340	numerator	20	137
PSLC.357	numerator	20	137
```

**Comment by 411an13** [comment]
Update: It seems like it was an issue with the original index names in the biom table, which had hyphens in them. I re-ran the workflow a third time in a completely new workflow directory and it made it further along (77% done instead of 38%) before encountering a different error related to the use of `iteritems` on a Series. I'll open a separate issue for that since I believe `iteritems` is deprecated now.
